/******************************
	CREATE ARRAY WITH GIFFS
*******************************/

var giffs = [
	"https://media.giphy.com/media/13HgwGsXF0aiGY/giphy.gif",
	"https://media.giphy.com/media/13HgwGsXF0aiGY/giphy.gif",
	"https://media.giphy.com/media/3m97D6EGGc4sE/giphy.gif",
	"https://media.giphy.com/media/3m97D6EGGc4sE/giphy.gif",
	// "https://media.giphy.com/media/FcHbO8FBMfsGY/giphy.gif",
	// "https://media.giphy.com/media/FcHbO8FBMfsGY/giphy.gif",
	// "https://media.giphy.com/media/4Z46NcIAOO3ok/giphy.gif",
	// "https://media.giphy.com/media/4Z46NcIAOO3ok/giphy.gif",
	// "https://media.giphy.com/media/gmg7s5bBQzlN6/giphy.gif",
	// "https://media.giphy.com/media/gmg7s5bBQzlN6/giphy.gif",
	// "https://media.giphy.com/media/UcK7JalnjCz0k/giphy.gif",
	// "https://media.giphy.com/media/UcK7JalnjCz0k/giphy.gif",
	// "https://media.giphy.com/media/EIJQbFyFFdo2s/giphy.gif",
	// "https://media.giphy.com/media/EIJQbFyFFdo2s/giphy.gif",
	// "https://media.giphy.com/media/26tn33aiTi1jkl6H6/giphy.gif",
	// "https://media.giphy.com/media/26tn33aiTi1jkl6H6/giphy.gif",
	// "https://media.giphy.com/media/aeIuSiMkcTsRO/giphy.gif",
	// "https://media.giphy.com/media/aeIuSiMkcTsRO/giphy.gif",
	// "https://media.giphy.com/media/wENb4DSakhJEA/giphy.gif",
	// "https://media.giphy.com/media/wENb4DSakhJEA/giphy.gif",
	// "https://media.giphy.com/media/143vPc6b08locw/giphy.gif",
	// "https://media.giphy.com/media/143vPc6b08locw/giphy.gif",
	// "https://media.giphy.com/media/xT8qBsOjMOcdeGJIU8/giphy.gif",
	// "https://media.giphy.com/media/xT8qBsOjMOcdeGJIU8/giphy.gif"
]

/******************************
	    GAME START
*******************************/

var startButton = document.querySelector('#start')
var board = document.querySelector('#container')
var scoreClicks = document.querySelector('#score')
var clicks = 0; // keeps track of overall trys to
var matches = 0; // keeps track state of game 
var arr = [] // use to keep track of comparing user events 
scoreClicks.innerText = 0;
// event listener for startbutton
startButton.addEventListener('click', startGame)

// STARTGAME
function startGame(){
	// ensures game board cannot get larger then array or be restarted by hitting start
	if(board.children.length > 0){
		alert('GAME IN PROGRESS')
	} else {
		shuffleArray(giffs)
		buildBorad()
	}
}

// SHUFFLE ARRAY
function shuffleArray(array){
	for(var i = array.length-1; i > 0; i--) {
		var j = Math.floor(Math.random() * (i+1))
		var itemValue = array[i]
		array[i] = array[j]
		array[j] = itemValue;
	}	
	return array
}

// CREATE BOARD
function buildBorad() {
	for(var i = 0; i < giffs.length; i++){
		// create elements
		var gameTile = document.createElement('div')
		var image = document.createElement('img')

		// set attributes
		gameTile.setAttribute('class', 'gameTile')
		image.setAttribute('id', 'card'+ i)
		image.setAttribute('class', 'giff')
		image.setAttribute('src', 'https://vignette.wikia.nocookie.net/southpark/images/0/0d/1a.jpg/revision/latest/scale-to-width-down/310?cb=20100826182516')

		// set event listener on image
		image.addEventListener('click', gameLogic)

		// append elements
		gameTile.append(image) 
		board.append(gameTile)

	}
}

/******************************
	    GAME LOGIC
*******************************/

// LOGIC
function gameLogic(event) {
		if(arr.length === 0) {
		// grab first event store it in varible	
			var firstClick = event.target.id
				// push id in array - can grab all infomration/set on element 
				arr.push(firstClick)
				var first = document.getElementById(firstClick)
				// upate src to be the index value in giffs by using the unique number generated by board creation id 
				// pass it to giffs array 
				first.src = giffs[Number(event.target.id.slice(4))]
				clicks++
				scoreClicks.innerText = clicks
		} else if(arr.length === 1) {
			//check to ensure you cannot click same element 
			if(arr.indexOf(event.target.id) > -1){
				return alert('INVALID SELECTION')
			}
			// grab second event store it in varible	
			var secondClick = event.target.id
				arr.push(secondClick)
				var second = document.getElementById(secondClick)
				second.src = giffs[Number(event.target.id.slice(4))]
				clicks++
				scoreClicks.innerText = clicks
				// compare giffs src 
				if (document.getElementById(arr[1]).src === document.getElementById(arr[0]).src) {
						matches++
						for(var i = 0; i < arr.length; i++){
							document.getElementById(arr[i]).removeEventListener('click', gameLogic)
						}
						// check winner 
						if(checkWinner(matches)){
							setTimeout(function(){alert('Congrats your a winner!')},2000)
							setTimeout(checkHighScore, 3000)
							setTimeout(restart,4000)
						} else {
							arr=[]
						}
				} else {
					setTimeout(function(){
						document.getElementById(arr[1]).src = 'https://vignette.wikia.nocookie.net/southpark/images/0/0d/1a.jpg/revision/latest/scale-to-width-down/310?cb=20100826182516'
					
					},750)
					setTimeout(function(){
						document.getElementById(arr[0]).src = 'https://vignette.wikia.nocookie.net/southpark/images/0/0d/1a.jpg/revision/latest/scale-to-width-down/310?cb=20100826182516'
					arr =[]	
					},1000)
				}
				
		}	

}

/******************************
	    HELPER FUNCTIONS 
*******************************/

// CHECK WINNER
function checkWinner(matches){
	return matches === giffs.length/2
}

// RESTART 
function restart(){
	//DONT FORGET TO RESET ARR
	arr = []
	clicks = 0;
	matches = 0;
	scoreClicks.innerText = 0;
	var children = document.querySelectorAll('.gameTile')
	for(var i = 0; i < children.length; i++){
		children[i].remove()
	}
}

/******************************
	    LOCAL STORAGE
*******************************/

function checkHighScore(){
	if(!localStorage.getItem('highScore')) {
		localStorage.setItem('highScore', clicks.toString())
		alert('Congrats you have highest score ever because no one has played!')
	} else if(localStorage.getItem('highScore')) {
		// HIGH SCORE IS LOWEST CLICKS
		if(Number(localStorage.getItem('highScore')) < clicks) {
			alert('Fantasic win but still not the all time lowest score')
		} else {
			// remove old score
			localStorage.removeItem('highSocre')
			// set new high schore 
			localStorage.setItem('highScore', clicks.toString())
			alert('Congrats you have highest score ever!')
		}

	}
}



