/******************************
	CREATE ARRAY WITH GIFFS
*******************************/

var giffs = [
	"https://media.giphy.com/media/13HgwGsXF0aiGY/giphy.gif",
	"https://media.giphy.com/media/13HgwGsXF0aiGY/giphy.gif",
	"https://media.giphy.com/media/3m97D6EGGc4sE/giphy.gif",
	"https://media.giphy.com/media/3m97D6EGGc4sE/giphy.gif",
	"https://media.giphy.com/media/FcHbO8FBMfsGY/giphy.gif",
	"https://media.giphy.com/media/FcHbO8FBMfsGY/giphy.gif",
	"https://media.giphy.com/media/4Z46NcIAOO3ok/giphy.gif",
	"https://media.giphy.com/media/4Z46NcIAOO3ok/giphy.gif",
	"https://media.giphy.com/media/gmg7s5bBQzlN6/giphy.gif",
	"https://media.giphy.com/media/gmg7s5bBQzlN6/giphy.gif",
	"https://media.giphy.com/media/UcK7JalnjCz0k/giphy.gif",
	"https://media.giphy.com/media/UcK7JalnjCz0k/giphy.gif",
	"https://media.giphy.com/media/EIJQbFyFFdo2s/giphy.gif",
	"https://media.giphy.com/media/EIJQbFyFFdo2s/giphy.gif",
	"https://media.giphy.com/media/26tn33aiTi1jkl6H6/giphy.gif",
	"https://media.giphy.com/media/26tn33aiTi1jkl6H6/giphy.gif",
	"https://media.giphy.com/media/aeIuSiMkcTsRO/giphy.gif",
	"https://media.giphy.com/media/aeIuSiMkcTsRO/giphy.gif",
	"https://media.giphy.com/media/wENb4DSakhJEA/giphy.gif",
	"https://media.giphy.com/media/wENb4DSakhJEA/giphy.gif",
	"https://media.giphy.com/media/143vPc6b08locw/giphy.gif",
	"https://media.giphy.com/media/143vPc6b08locw/giphy.gif",
	"https://media.giphy.com/media/xT8qBsOjMOcdeGJIU8/giphy.gif",
	"https://media.giphy.com/media/xT8qBsOjMOcdeGJIU8/giphy.gif"
]

/******************************
	    GAME START
*******************************/

var startButton = document.querySelector('#start')
var board = document.querySelector('#container')
console.log(board.children)
var clicks = 0;
var matches = 0;

// event listener for startbutton
startButton.addEventListener('click', startGame)

//STARTGAME
function startGame(){
	// ensures game board cannot get larger
	if(board.children.length > 0){
		alert('GAME IN PROGRESS')
	} 

	shuffleArray(giffs)
	buildBorad()
			
}

function shuffleArray(array){
	for(var i = array.length-1; i > 0; i--) {
		var j = Math.floor(Math.random() * (i+1))
		var itemValue = array[i]
		array[i] = array[j]
		array[j] = itemValue;
	}	
	return array
}

// CREATE BOARD
function buildBorad() {
	for(var i = 0; i < giffs.length; i++){
		// create elements
		var gameTile = document.createElement('div')
		var image = document.createElement('img')

		// set attributes
		gameTile.setAttribute('class', 'gameTile')
		image.setAttribute('id', 'card'+ i)
		image.setAttribute('class', 'giff')
		image.setAttribute('src', 'https://vignette.wikia.nocookie.net/southpark/images/0/0d/1a.jpg/revision/latest/scale-to-width-down/310?cb=20100826182516')

		// set event listener on image
		image.addEventListener('click', gameLogic)

		// append elements
		gameTile.append(image) 
		board.append(gameTile)

	}
}

/******************************
	    GAME LOGIC
*******************************/

// Logic
function gameLogic(event){
	// Somehow keep track of clicks and reset 
	// grab first event store somewhere
		var firstClick = something
			// upate src to be the index value in giffs by using the unique number generated by board creation id 
			event.target.src = giffs[Number(event.target.id.slice(4))]
			clicks++

	// grab second event store it somewhere 
		var secondClick = something 
			/// upate src to be the index value in giffs by using the unique number generated by board creation id 
			event.target.src = giffs[Number(event.target.id.slice(4))]
			clicks++
	// compare giffs src 
			// if firsClick === secondClick 
			matches++
			// then run checkWinner function

	// If no winner reset images to original
}

// check winner 
function checkWinner(){
	if(matches === giffs.length/2){
		alert('Game will restart')
		// show restart button 
	}
}

function restart(){
	clicks = 0;
	matches = 0;
	while(board.children.length !== 0){
		board.remove(gameTile)
	}
}





